apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk8r-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sk8r-app
  template:
    metadata:
      labels:
        app: sk8r-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: sk8r-app
        image: mvkdev/sk8r-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: PROMETHEUS_URL
          value: "http://kube-prometheus-stack-prometheus.monitoring:9090"

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
