apiVersion: v1
kind: Service
metadata:
  name: sk8tes-service
spec:
  selector:
    app: sk8tes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  # If you want to request a specific IP from your MetalLB pool, uncomment the following line
  # loadBalancerIP: <your-desired-ip>
